#build stage for a Node.js application
FROM node:12.22.5-alpine3.14 as build-stage
WORKDIR /var/www/
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#production stage
FROM nginx:1.21.5-alpine as production-stage
COPY --from=build-stage /var/www/dist/angular-docker-one /var/www
COPY --from=build-stage /var/www/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]