version: '3'
services:
  app1:
    image: nginx:1.21.5-alpine
    container_name: app1
    volumes:
      - ./dist/angular-docker-one:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  app2:
    image: nginx:1.21.5-alpine
    container_name: app2
    volumes:
      - ./dist/angular-docker-two:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    volumes:
      - ./load_balancer.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
