version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-angular-docker
    working_dir: /var/www/
    command: npm run start
    ports:
      - 8080:80
    volumes:
      - './src:/var/www/src'
